---
- name: install debian tools
  become: yes
  apt: 
    name:
      - bat
      - curl
      # - fd-find
      - fzf
      - htop
      - jq
      - nodejs
      - ripgrep
      - tldr
      - tmux
      - wget
      - zsh
      - ninja-build 
      - gettext 
      - libtool 
      - libtool-bin 
      - autoconf 
      - automake 
      - cmake 
      - g++ 
      - pkg-config 
      - unzip 
      - doxygen
  when: ansible_os_family == "Debian"

- name: install redhat tools
  become: yes
  yum: 
    name:
      - bat
      - curl
      - fd-find
      - fzf
      - htop
      - jq
      - nodejs
      - ripgrep
      - tmux
      - wget
      - zsh
      - ninja-build 
      - libtool 
      - autoconf 
      - automake 
      - cmake 
      - gcc 
      - gcc-c++ 
      - make 
      - pkgconfig 
      - unzip 
      - patch 
      - gettext 
  when: ansible_os_family == "RedHat"

- name: install lazygit 
  become: yes
  shell: |
    LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
    curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
    tar xf lazygit.tar.gz lazygit
    install lazygit /usr/local/bin
    rm -rf lazygit*


