---
- name: install debian tools
  become: yes
  apt: 
    name:
      - bat
      - curl
      # - fd-find
      - fzf
      - htop
      - jq
      - nodejs
      - ripgrep
      - tmux
      - wget
      - zsh
  when: ansible_os_family == "Debian"

- name: install redhat tools
  become: yes
  yum: 
    name:
      - bat
      - curl
      - fd-find
      - fzf
      - htop
      - jq
      - nodejs
      - ripgrep
      - tmux
      - wget
      - zsh
  when: ansible_os_family == "RedHat"

- name: check neovim installed
  stat: path="/usr/bin/nvim"
  register: bin_nvim 
  changed_when: bin_nvim.stat.exists == False

- name: download neovim
  get_url: 
    url="https://github.com/neovim/neovim/releases/latest/download/nvim.appimage" 
    dest="{{ dotfiles_user_home }}/nvim.appimage"
    mode=0755
  register: neovim_downloaded
  when: not bin_nvim.stat.exists

- name: check if downloaded image exists
  stat: path="{{ dotfiles_user_home }}/nvim.appimage"
  register: neovim_downloaded_image

- name: move neovim to /usr/bin
  become: yes
  command: mv {{ dotfiles_user_home }}/nvim.appimage /usr/bin/nvim
  register: neovim_moved
  when: neovim_downloaded_image.stat.exists

- name: install lazygit 
  become: yes
  shell: |
    LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
    curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
    tar xf lazygit.tar.gz lazygit
    install lazygit /usr/local/bin

- name: check miniconda installed
  stat: path="{{ miniconda_home }}/bin/conda"
  register: bin_conda 
  changed_when: bin_conda.stat.exists == False

- name: download miniconda
  get_url:
    url="https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    dest="/tmp/miniconda.sh"
    mode=0744
  register: miniconda_downloaded
  when: not bin_conda.stat.exists

- name: install miniconda
  shell: "/tmp/miniconda.sh -b -p {{ miniconda_home }} creates={{ miniconda_home }} executable=/bin/bash"
  register: miniconda_installed
  when: miniconda_downloaded is success or bin_conda.exists
  notify: 
    - remove miniconda script
    - update conda to latest 
