- name: Find config files
  find: 
    paths: ~/dotfiles/config/
    recurse: no
    file_type: any
    hidden: yes
  register: dot_config

- name: Check for oh-my-zsh installation
  stat: "path=~/.oh-my-zsh"
  register: oh_my_zsh_stat

- name: Install oh-my-zsh
  raw: "sh -c \"$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)\""
  when: not oh_my_zsh_stat.stat.exists

- name: Check for .zshrc
  stat: path="{{dotfiles_user_home}}/.zshrc"
  register: zshrc_stat

- name: Symlink .zshrc
  file:
    src: "{{ dotfiles_home }}/config/zshrc"
    dest: "{{ dotfiles_user_home }}/.zshrc"
    state: link
    force: yes

- name: Symlink p10k.zsh
  file:
    src: "{{ dotfiles_home }}/config/p10k.zsh"
    dest: "{{ dotfiles_user_home }}/.p10k.zsh"
    state: link
    force: yes

- name: Symlink tmux.conf
  file:
    src: "{{ dotfiles_home }}/config/tmux.conf"
    dest: "{{ dotfiles_user_home }}/.tmux.conf"
    state: link
    force: yes

- name: Check if nvim config directory exists
  stat: "path={{ dotfiles_user_home }}/.config/nvim"
  register: nvim_config

- name: Create nvim config directory 
  file: 
    path: "{{ dotfiles_user_home }}/.config/nvim"
    state: directory
    mode: 0755
  when: not nvim_config.stat.exists

- name: Symlink init.lua
  file: 
    src: "{{ dotfiles_home }}/config/init.lua"
    dest: "{{ dotfiles_user_home }}/.config/nvim/init.lua"
    state: link
    force: yes

- name: Remove old ipython config
  file: 
    path: "{{ dotfiles_user_home }}/.ipython/profile_default/ipython_config.py"
    state: absent

- name: Check if ipython config directory exists
  stat: "path={{ dotfiles_user_home }}/.ipython/profile_default"
  register: ipython_config

- name: Create ipython config directory
  file: 
    path: "{{ dotfiles_user_home }}/.ipython/profile_default"
    state: directory
    mode: 0755
  when: not ipython_config.stat.exists

- name: Symlink ipython_config
  file: 
    src: "{{ dotfiles_home }}/config/ipython_config.py"
    dest: "{{ dotfiles_user_home }}/.ipython/profile_default/ipython_config.py"
    state: link
    force: yes
