- name: check neovim installed
  stat: path="/usr/bin/nvim"
  register: bin_nvim 
  changed_when: bin_nvim.stat.exists == False
  tags: neovim, neovim-build

- name: clone neovim
  git: 
    repo: https://github.com/neovim/neovim.git
    dest: "{{ user_home }}/neovim"
    version: stable
  register: neovim_cloned
  when: not bin_nvim.stat.exists
  tags: neovim-build

- name: clean up artifacts 
  community.general.make: 
    chdir: "{{ user_home }}/neovim"
    target: distclean
    make: "/usr/bin/make"
  tags: neovim-build

- name: build neovim
  community.general.make: 
    chdir: "{{ user_home }}/neovim"
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo
    target: install
    make: "/usr/bin/make"
  register: neovim_build
  when: neovim_cloned.stat.isdir is defined and neovim_cloned.stat.isdir
  tags: neovim-build

- name: install neovim
  become: yes
  make:
    chdir: "{{ user_home }}/neovim"
    target: install
  register: neovim_install
  tags: neovim-build

